process.env.NODE_ENV = 'test'
process.env.JWT_SECRET = 'test-jwt-secret'
process.env.JWT_ISSUER = 'test-issuer'
process.env.JWT_AUDIENCE = 'test-audience'
process.env.JWT_EXPIRES_IN = '3600'
process.env.JWT_REFRESH_SECRET = 'test-jwt-refresh-secret'
process.env.JWT_REFRESH_EXPIRES_IN = '86400'
process.env.COOKIES_SECRET = 'test-cookies-secret'
